### ISSUE TITLE
Fluid package dialog

### ISSUE THREAD

**Issue by olavis** [equinor/mercury#37]
First mockup:
<img width="424" alt="Screenshot 2022-09-20 at 14 10 04" src="https://user-images.githubusercontent.com/38139899/191260376-d2719400-1b6e-4186-9be5-cb1b80ae0ee3.png">

The dialog:
- [x] can be opened/closed #53 
- [x] has the title `Fluid package` #53
- [x] #120
- [x] can be used to create and save a new fluid package #53
- [x] has a delete-button that #53
  - [x] is outlined and color=danger #53
  - [ ] deletes the current fluid package (confirm choice?)
  - [x] is disabled when no existing fluid-package is selected
- [x] has a save-button that #53
  - [ ] is enabled only when properties of the current fluid has changed
  - [x] #74
- [x] has a cancel-button that #53
  - [x] is outlined #53
  - [x] closes the dialog without saving changes #53
- [x] has input textfields for name and description #53
- [x]  has a autocomplete that can be used to select/deselect chemical components in the table; the most common components/the current fluid package's components are preselected
  - [x] #84 
  - [x] #97
- [x] has styling that aligns its children like the example (ish)
- [x] has tests for the behaviour listed above
